### ISSUE TITLE
unhandled SQLiteException

### ISSUE THREAD

**Issue by ghost** [mbrit/ProgrammingMetroStyle#1]
Hello,

I tried to run chapter 04 on Release Preview and got this:

Could not open database file: C:\Users\Jean-François\AppData\Local\Packages\569e8a16-efb8-4992-ada5-7407fecb3dee_fv7d1kf84c3t4\LocalState\StreetFoo-system.db (14)

Any idea on what is going here ?

Regards
Kako78

**Comment by mbrit** [comment]
No - not immediately. I need more information, I think.

Do you have a full exception dump?

Is that file actually there?

Where did you get the sqlite3.dll from that you're using?

**Comment by ghost** [comment]
The stack trace is:
   at SQLite.SQLiteConnection..ctor(String databasePath) in c:\Dev\Samples\mbrit-ProgrammingMetroStyle-53e4f57\mbrit-ProgrammingMetroStyle-53e4f57\Chapter04\StreetFoo.Client\StreetFoo.Client\Data\SQLite.cs:line 110
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString) in c:\Dev\Samples\mbrit-ProgrammingMetroStyle-53e4f57\mbrit-ProgrammingMetroStyle-53e4f57\Chapter04\StreetFoo.Client\StreetFoo.Client\Data\SQLiteAsync.cs:line 428
   at SQLite.SQLiteConnectionPool.Entry..ctor(SQLiteConnectionString connectionString) in c:\Dev\Samples\mbrit-ProgrammingMetroStyle-53e4f57\mbrit-ProgrammingMetroStyle-53e4f57\Chapter04\StreetFoo.Client\StreetFoo.Client\Data\SQLiteAsync.cs:line 360
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString) in c:\Dev\Samples\mbrit-ProgrammingMetroStyle-53e4f57\mbrit-ProgrammingMetroStyle-53e4f57\Chapter04\StreetFoo.Client\StreetFoo.Client\Data\SQLiteAsync.cs:line 393
   at SQLite.SQLiteAsyncConnection.GetConnection() in c:\Dev\Samples\mbrit-ProgrammingMetroStyle-53e4f57\mbrit-ProgrammingMetroStyle-53e4f57\Chapter04\StreetFoo.Client\StreetFoo.Client\Data\SQLiteAsync.cs:line 44
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass1.<CreateTablesAsync>b__0() in c:\Dev\Samples\mbrit-ProgrammingMetroStyle-53e4f57\mbrit-ProgrammingMetroStyle-53e4f57\Chapter04\StreetFoo.Client\StreetFoo.Client\Data\SQLiteAsync.cs:line 91
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

The database doesn't exist yet. I downloaded the code from Git, compiled and ran. So sqlite3 came with your source code.

I tried to build a sample SQLite metro app and got the exact same problem (using sqlite3.dll from sqlite.org).
Really weird. I couldn't figure out what is happening here.

**Comment by ghost** [comment]
ok I found the problem (well Tim Heuer actully did). The problem occurs because of the cedilla in the DB path.
Not sure however whether it's a sqlite or sqlite-net issue...

**Comment by mbrit** [comment]
Yes, the cedilla shouldn't be in there - is that in the code for the download?

**Comment by ghost** [comment]
The cedilla comes from my user name. The path for the DB is built from Windows.Storage.ApplicationData.Current.LocalFolder.Path which for me returns something like "C:\Users\Jean-François\AppData..."

-----Message initial-----
De: Matthew Baxter-Reynolds (@mbrit) reply@reply.github.com
Envoyé:    jeu. 28-06-2012 16:32
Sujet:  Re: [ProgrammingMetroStyle] unhandled SQLiteException (#1)
À: Jean-François Guyet jeanfrancois@guyet.net;

**Comment by mbrit** [comment]
Ah, gotcha on the cedilla. I thought you meant tilde. :-)
